title: 'air'
description: "Portfolio"
baseurl: "air"
url: ""

header_pages:
  - index.md
  - about.md
  - contact.md

style: hacker

footer: ''

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
